# Generated by Django 6.1 on 2026-08-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ten benh')),
                ('infor', models.TextField(verbose_name='Thong tin ve benh')),
                ('prompt', models.TextField(blank=True, help_text='Thong tin mo ta benh de dua len LLM, cai nay admin dat', verbose_name='prompt')),
                ('img_ex', models.ImageField(blank=True, null=True, upload_to='diseases/', verbose_name='Hinh minh hoa cho benh')),
            ],
            options={
                'verbose_name': 'Loai benh',
                'verbose_name_plural': 'So tay benh tren cay mai',
                'ordering': ['name'],
            },
        ),
    ]
